apiVersion: v2
name: juicefs-csi-driver
description: A Helm chart for JuiceFS CSI Driver
type: application
version: 0.22.3
appVersion: 0.26.2
kubeVersion: ">=1.14.0-0"
home: https://github.com/juicedata/juicefs-csi-driver
sources:
  - https://github.com/juicedata/juicefs-csi-driver
icon: https://s.juicefs.com/static/jfs/logo.svg
maintainers:
  - email: team@juicedata.io
    name: Juicedata Inc.
    url: https://juicefs.com
keywords:
  - juicefs
  - csi
